import "./alloy_sig"
import "./alloy_sigEx"
import "./alloy_sig_reference"
import "./alloy_relation"
import "./alloy_sig_empty"
import "./alloy_sigEx_empty"
import "./alloy_sigIn"
import "./alloy_sigIn_empty"